### ISSUE TITLE
onHeightChange not fired when change minHeight property in style

### ISSUE THREAD

**Issue by DmitriyMaximov** [Andarist/react-textarea-autosize#244]
onHeightChange not fired when change minHeight property in style.

**Comment by Andarist** [comment]
That's true, minHeight is not being handled through the internal `height` state, but rather just through CSS. 

Seems like it is something that could work though, I've been meaning to rewrite the internals for quite some time, so that would be a good time to look into your issue. But I can't promise any ETA, been really busy lately.

**Comment by Andarist** [comment]
I've dropped handling `props.style.minHeight` entirely. Instead I recommend just using `minRows` prop. If you have a compelling use case for using style prop to control this - please let me know by creating a new issue.
