### ISSUE TITLE
Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.

### ISSUE THREAD

**Issue by onoufriosm** [Andarist/react-textarea-autosize#259]
We get this error from time to time. Wasn't able to reproduce but our clients have bumped into this bug.

![image](https://user-images.githubusercontent.com/12834779/73347561-b731de80-427f-11ea-8bee-de0203e4bece.png)

Happened recently on:
1. browserName: Chrome, browserVersion: 71.0.3578, locale: ru-RU, osName: Linux
2. browserName: Chrome, browserVersion: 79.0.3945, locale: sv-SE, osName: Windows 10.0

Any ideas why this is happening?

**Comment by tonoslav** [comment]
Something new with this , its already year almost @Andarist , can you add some check above getComputedStyle?
For example 
```js
if (node === null) { // or if (!(node && node.nodeType))
    return null;
}
```
I think problem is maybe with already unmounted/removed elements

**Comment by Andarist** [comment]
Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

**Comment by tonoslav** [comment]
> Please always try to share a repro case in a runnable form - either by providing a git repository to clone or a codesandbox. OSS maintainers usually can't afford the time to set up the repro, even if exact steps are given.

I know @Andarist but the problem is I cannot reproduce it but I know I have hundreds of error events in my logs and that error message is kinda self explanatory what should some if condition solve imo, the same as you have another one after that with **style** variable

Not sure if it could help but I have this code in my app which I need to force some recalculation of other package I use

```ts
const fakeWindowResize = () => {
    let evt: Event
    if (typeof Event === 'function') {
        evt = new Event('resize')
    } else {
        const evtGen: LooseObject = window.document.createEvent('UIEvents')
        if (evtGen && evtGen.initUIEvent) {
            evt = evtGen.initUIEvent('resize', true, false, window, 0)
        }
    }
    window.dispatchEvent(evt)
}

setInterval(fakeWindowResize, 2000)
```

Which simulate resize event and I think your package catch this and do something what cause this error but only sometimes, thats why I think it is because of some element (textarea) was unmounted already, but it is hard to reproduce on purpose

**Comment by Andarist** [comment]
Well, I understand that the fix seems to be an easy one but I refuse to patch things that I don't understand on principle. It often leads to masking a true problem. We should be able to write a test covering for this problem but we can only do so if we know what the problem is. I've re-examined the code and I don't see how this could happen (however, I believe you that it happens).

**Comment by tonoslav** [comment]
> Well, I understand that the fix seems to be an easy one but I refuse to patch things that I don't understand on principle. It often leads to masking a true problem. We should be able to write a test covering for this problem but we can only do so if we know what the problem is. I've re-examined the code and I don't see how this could happen (however, I believe you that it happens).

I think problem might be because of new react version which runs cleanup effects async
![image](https://user-images.githubusercontent.com/3399021/101239095-2caedc80-36e5-11eb-8094-5cc9e6656cde.png)
https://github.com/facebook/react/blob/master/CHANGELOG.md#1700-october-20-2020

So it might be something like this
1. listen to resize - https://github.com/Andarist/react-textarea-autosize/blob/a1fc99f79fa28b5518f1c5e937f765ace46f68c2/src/index.tsx#L96
2. unmount textarea (for example due to redirect in my app)
3. random **fakeWindowResize** triggered by my app (see code in messages before)
4. resizeTextarea triggered - https://github.com/Andarist/react-textarea-autosize/blob/a1fc99f79fa28b5518f1c5e937f765ace46f68c2/src/index.tsx#L59
5. trying to resize unmounted element which cause this error
6. call hook cleanup (async thats why it is not called after step 2) - https://github.com/Andarist/react-textarea-autosize/blob/a1fc99f79fa28b5518f1c5e937f765ace46f68c2/src/index.tsx#L96

In older version step 6. would be called right after step 2. which wouldn't cause this error to happen and thats why it is almost impossible to repro this, cause its unpredictable but possible and thats why I think is required to check


maybe this thread might help you to understand better the problem
https://github.com/facebook/react/issues/19671

**Comment by Andarist** [comment]
And this makes sense! I knew about this change in React 17 but it hasnt bitten me yet so I havent connected the dots. The original issue was reported before React 17 though. Either way - I propose to move the resize listener to a layout effect. Would you like to prepare a PR for this?
