### ISSUE TITLE
Broken Demo

### ISSUE THREAD

**Issue by eyalcohen4** [Andarist/react-textarea-autosize#294]
Hi, thanks for the lib!

The demo website is broken for me and doesn't show anything in production (both Chrome & FE, and in incognito mode).
Also no special error in the console.

I've cloned the repo and run `docs:dev`, and the docs worked. 
Guess it's something with the deploy script.

LMK if I can help!

**Comment by Andarist** [comment]
Yeah - I was trying to fix it (https://github.com/Andarist/react-textarea-autosize/pull/295), but couldn't configure it correctly with Parcel 2 (I thought it would actually be easier to migrate to Parcel 2 rather than fixing Parcel 1 config, but maybe that was a mistake). 

If you could take a look at this and fix it - I would highly appreciate it as I couldn't get time to do it for the past few months.

**Comment by Andarist** [comment]
I've managed to finally fix it. The example page is up and running.
